### ISSUE TITLE
Refactoring: use same mechanism to manage/load check rules

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode-ios#15]
To prepare future iOS specification rules centralization (see: green-code-initiative/ecoCode#92), please use:
* `org.sonarsource.analyzer.commons.RuleMetadataLoader`
* `@org.sonar.check.Rule` to identify each check Rules
* add `@org.sonarsource.analyzer.commons.annotations.DeprecatedRuleKey`to manage rule key renaming
* one JSON and HTML for each rules

(NB: I will work on this issue. You can assign this issue to me)

**Comment by dedece35** [comment]
Hi @jycr and @zippy1978 

what do you think about this issue @zippy1978 ?
