### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by zippy1978** [green-code-initiative/ecoCode-ios#2]
Checklist :

- [x] Manual testing with analysis
- [x] Documentation check
- [x] Version bump
- [x] Release

**Comment by dedece35** [comment]
Hi @zippy1978,
sorry, I don't understand this issue.
do you want me to create the new 1.1.0 release after compatibility SonarQube 10.0 check (https://github.com/green-code-initiative/ecoCode-mobile/issues/66) ?
if yes, I think we have to change SonarQube version in Docker files before, no ? (and wait for android check by @jhertout )

Secondaly, what are this check-list ? is your checking list before I create the new release ?

**Comment by zippy1978** [comment]
Hi @dedece35,
This issue is actually a reminder to myself (things to check before releaing).
I will change SonarQube version to 10 in Dockerfile as well.

I will create a PR with the changes and assign it to you.
An once you approve it, I will create the tag 1.1.0 if you agree.
